### ISSUE TITLE
Interactive Playground background color

### ISSUE THREAD

**Issue by tyler36** [ambidexterich/vscode-fresh-material#10]
Thanks for the themes, I think they look great and it's nice to have the color variations (indigo is soothing).

I'm not sure if it's intended or not, but the "Interactive Playground" looks pretty bad. 
![vscode issue](https://user-images.githubusercontent.com/7234392/36358958-872c12a0-1559-11e8-8e6f-e4fff60af234.jpg)

Granted, this is not an area that I visit after so I have no idea if this "bug" has been there for a while or not but it doesnt feel "intended" to me and make the code pretty unreadable. The "issue" appears in all theme variations available.

I think you need to set the ```walkThrough.embeddedEditorBackground``` color to something. 
If I use the "Generate theme from current settings" option, it show up as
```
""walkThrough.embeddedEditorBackground": "#ffffff",
```

OS: Win10
Visual Code: 1.20.1

**Comment by ambidexterich** [comment]
Thanks for reporting this and I'm glad you like the theme. I just pushed a fix. When I don't know what something is or where to see it, I leave it blank which causes it to show up red.

**Comment by tyler36** [comment]
No problems.

Just updated the extension and can confirm working. 
Thanks for the quick response / fix! 🥇 

And thanks again for the beautiful extension.
