### ISSUE TITLE
Disable output theming?

### ISSUE THREAD

**Issue by tyler36** [ambidexterich/vscode-fresh-material#12]
I'm trying to get color in my debug / output panel and came across Output Colorizer (https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer)

Unfortunately, my favorite theme, Fresh-material: Indigo, seems to be overriding it.

What I'd like to be able to do is:
- Display UI in "Fresh-material: Indigo" theme
- Display  ```debug / output panel background ``` in "Fresh-material: Indigo" theme 
- Display  ```debug / output panel text``` with Output Colorized overriding "Fresh-material: Indigo" where applicable.

Is this even possible?

**Comment by ambidexterich** [comment]
Thanks for reporting this, I'm not positive it is possible but I will definitely look into it.

**Comment by tyler36** [comment]
OK ... after a loooong think. I started playing with the theme. I realized I don't really need Output Colorizer.
I can overrride the the theme using my own settings file.

```json
    "editor.tokenColorCustomizations": {
        "[Fresh Material - Indigo]": {
            "textMateRules": [
                {
                    "name": "PHPUnit console filename",
                    "scope": "storage",
                    "settings": {
                        "foreground": "#e5c07b"
                    }
                },
                {
                    "name": "PHPUnit console versions numbers",
                    "scope": [
                        "support.type",
                        "support.variable"
                    ],
                    "settings": {
                        "foreground": "#d19a66"
                    }
                },
                {
                    "name": "PHPUnit console ERROR",
                    "scope": "markup.deleted",
                    "settings": {
                        "foreground": "#e06c75"
                    }
                },
                {
                    "name": "PHPUnit console RISKY",
                    "scope": "markup.changed",
                    "settings": {
                        "foreground": "#e5c07b"
                    }
                },
                {
                    "name": "PHPUnit console SUCCESS",
                    "scope": "markup.inserted",
                    "settings": {
                        "foreground": "#98c379"
                    }
                },
         ]
    }
}
```

The settings above produce the image below (with a green text when tests pass). It's not the same level of pretty I get from the CLI, but it lets me keep Fresh Material: Indigo and gives me colorized clues for my tests.

![colored-phpunit](https://user-images.githubusercontent.com/7234392/102955478-55bed200-4519-11eb-96fa-09893dc051e3.jpg)
