### ISSUE TITLE
Syntax highlighting of diff/patch file not working after enabling Fresh Material theme

### ISSUE THREAD

**Issue by rsau** [ambidexterich/vscode-fresh-material#13]
Hi   

When I enable any Fresh Material color theme, syntax highlight doesn't work for diff files. 

**With Fresh Material theme enabled.**  
   
![with-fresh-material](https://user-images.githubusercontent.com/29110027/75395600-dbe4a900-5946-11ea-9d57-e8403db19ce4.png)   

**Without Fresh material**  
 
![without-fresh-material](https://user-images.githubusercontent.com/29110027/75395607-df783000-5946-11ea-945e-c085f3e3c604.png)

**Comment by tyler36** [comment]
Confirmed ... I'm not getting anything either.

However, I a found a (partial) solution while trying to resolve another issue, #12 . 
```
    "editor.tokenColorCustomizations": {
        "[Fresh Material - Indigo]": {
            "textMateRules": [
                {
                    "name": "PHPUnit console ERROR",
                    "scope": "markup.deleted",
                    "settings": {
                        "foreground": "#e06c75"
                    }
                },
                {
                    "name": "PHPUnit console SUCCESS",
                    "scope": "markup.inserted",
                    "settings": {
                        "foreground": "#98c379"
                    }
                },
            ]
        },
    },
```
The above:
- adds the 'red' color from indigo theme for deletions
- add the 'green' color from  indigo theme for additions

The "name" in "textMateRules" can be anything, but for my use case, I was trying to theme the PHPUnit output in the terminal and I got 'diff' files as a bonus.

**Comment by ambidexterich** [comment]
Thanks for reporting this. VSCode has changed their color keys in later versions. I am currently going through the process of testing the changes to make sure I got everything.

**Comment by tyler36** [comment]
Thank you for the update. 

I'm happy to test it before release if you need a confirmation (it's Friday morning here though so weekend might delay a response)

**Comment by tyler36** [comment]
Confirmed on v`2.3.9`

The recent update makes diff files so beautiful!
