### ISSUE TITLE
Unstyled remote element

### ISSUE THREAD

**Issue by tyler36** [ambidexterich/vscode-fresh-material#14]
I think there might be an issue with coloring of the `remote` box: remote-containers, remote-ssh & remote-wsl. 

When these extensions are installed a box appears in the bottom of the toolbar.
The default shows a highlight box thats not too overbearing.
![vscode-default](https://user-images.githubusercontent.com/7234392/114844452-c9ad1f00-9e15-11eb-910b-170bd5a3aea1.png)

On "Fresh Material - Indigo" theme,
1. It appears as white with gray text which feels "too bright" for a dark theme and makes the text hard to read.
![vscode-remote-wsl](https://user-images.githubusercontent.com/7234392/114844391-ba2dd600-9e15-11eb-9b5e-08d16256a6f6.png)

2. On hover, the box changes to a dark gray with gray text which become unreadable.
![vscode-remote-wsl-hover](https://user-images.githubusercontent.com/7234392/114844395-bb5f0300-9e15-11eb-974b-18875998e829.png)

**Comment by ambidexterich** [comment]
I should have a fix for this in the coming days. VSCode changed the keys the used to make colors to their UI and I am in the process of using the new version to make sure I got everything.

**Comment by tyler36** [comment]
Thank you for the update. I'm happy to test it before release if you need a confirmation (it's Friday morning here though so weekend might delay a response)

**Comment by tyler36** [comment]
Confirmed on v`2.3.9`

Thank you for updating the theme. 
- Remote background color always appears as a "light green" regardless of theme color.  First reaction was it was a bug and should be the theme hightlight color (Eg. indigo, blue, etc). But I'm not a designer and the splash of color is starting to grow on me.
- No hover effect. Personally, I don't think it's needed but poiting it out for consistency with other buttons.
- Clicking the button cause the green background to disappear and the text to be ureadable as shown in OP screenshot #2. Again,  not a problem, but simple feedback.

Thank for taking the time to update the theme over the years. I *really love* this theme.

**Comment by ambidexterich** [comment]
Thanks for the feedback:
1. You are right. I forgot to update all of the themes. I will create a bug and fix
2. This is because there is no specific way to style the remote button, it overlays the statusbar hover color over top of the remote color.
3. I don't use the remote connect so I forgot to click on it. I will create a bug and fix

Thanks again

**Comment by ambidexterich** [comment]
I fixed this in the develop branch. Would you be willing to test it out before I push it to the marketplace?
