### ISSUE TITLE
Rust language support

### ISSUE THREAD

**Issue by CodeBizarre** [ambidexterich/vscode-fresh-material#6]
Enjoying the theme so far, however Rust language support seems lacking. 

Short rust code example:
```rust
extern crate piston_window;

use piston_window::*;

fn main() {
    let mut window: PistonWindow = 
        WindowSettings::new("Hello Piston!", [640, 480])
        .exit_on_esc(true).build().unwrap();
    while let Some(e) = window.next() {
        window.draw_2d(&e, |c, g| {
            clear([1.0; 4], g);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      c.transform, g);
        });
    }
}
```
Attached is an image of how Rust code looks using this theme currently.
![rust](https://cloud.githubusercontent.com/assets/23280807/25643689/8700f086-2f66-11e7-9497-a8f510b849e4.png)

**Comment by ambidexterich** [comment]
Thanks, I can add that shortly

**Comment by ambidexterich** [comment]
Done. VSCode's Rust syntax parser isn't great so there will still be quite a bit of gray but I added what I could.
