### ISSUE TITLE
Changes to the gutter coloring after the April update

### ISSUE THREAD

**Issue by esimkowitz** [ambidexterich/vscode-fresh-material#8]
I just updated VS Code to the April 2017 update and I noticed that it affected the way the gutter in the editor is displayed. There is now a solid red background to the gutter. The color of the text for the currently-open file in the Explorer sidebar is also that same red color.

I tested this on both macOS and Windows 10 (64-bit).

**Comment by ambidexterich** [comment]
Thanks, I'm working on an update now and should have it soon.

**Comment by ambidexterich** [comment]
Just published an update. If you find anything else let me know. Thanks!
