### ISSUE TITLE
Some issue with status bar?

### ISSUE THREAD

**Issue by eudennis** [ambidexterich/vscode-fresh-material#9]
I just installed this theme, but the statusbar color is red :( I'm not facing this issue with other themes.

![screenshot from 2017-09-11 19-05-46](https://user-images.githubusercontent.com/1117340/30299108-98ded2ca-9724-11e7-8862-b43b2109b9d2.png)

**Comment by ambidexterich** [comment]
Just had a couple of questions:

Which color are you using? 
Are you seeing this in other colors?
Which OS are you on?
Which version of VS Code are you using?

**Comment by eudennis** [comment]
Yes, with any color. 

Ubuntu 17.04, VS 1.16.

But is strange, because I noticed now that this is happening only when open the VSCode without any file, opening anything from terminal it's fine.

**Comment by ambidexterich** [comment]
Thanks for submitting this. I just pushed a new version that should fix this.
